project:
  type: website
  output-dir: docs

website:
  title: "Quantitative Geographie: Mobile Gesellschaft"
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Intro
      - 01_basics.qmd
      - 02_data_manipulation.qmd
      - 05_regional_profile.qmd
      - 03_sequenzanalyse.qmd
      - 04_mapping.qmd


format:
  html:
    theme:
      - default
      - brand
    css: styles.css
    logo: images/logo.jpg
    toc: true
    execute:
      echo: true
      warning: false
      message: false
      fig-width: 8       # default width in inches
      fig-height: 6      # default height in inches


